version: "3"
services:
  mqtt:
    host: mqtt://192.168.8.178
    image: toke/mosquitto
    network_mode: bridge
    container_name: mqtt
    expose:
      - 1883
    ports:
      - 1883:1883
    restart: unless-stopped

    #   mosquitto_pub -t "first_topic" -m "Hi"
    #   mosquitto_sub -t "first_topic" -v
